### ISSUE TITLE
BUG: Multiplayer help (F1) menu / change cutting size

### ISSUE THREAD

**Issue by Gamerkuipers** [Timmeey86/FS22_ForestryHelper#20]
I have just downloaded the version 1.0.5 to fix a multiplayer issue but now we cannot see the the F1 help menu anymore for the keybinds and can no longer change the cutting size and probably the other key binds as well.

We are on a client hosted multiplayer game. If I am in the game solo or with a friend it wont work. It did work in singleplayer
![image](https://github.com/Timmeey86/FS22_ForestryHelper/assets/55430516/6af68c9a-295c-463b-a8e6-45f7c0f70419)

**Comment by Timmeey86** [comment]
I only tested the mutliplayer version on a dedicated server, it's possible the current code doesn't work properly if the server host is also a player. I'll look into it

**Comment by Timmeey86** [comment]
If I understand you right, it also doesn't work for you if you create a local multiplayer game and it's only you in there?

I just tested the following, and that worked:

1. Create a local multiplayer game
2. Select an existing single player save game
3. Start the game
4. Join a farm
5. Select my chainsaw
=> Menu options show up

Also:

1. Create a local multiplayer game
2. Select a new save
3. Start a new game
4. Create and join a farm
5. Buy a chainsaw
6. Select the chainsaw
=> Menu options show up

**Comment by Gamerkuipers** [comment]
Okay so now I just joined my local multiplayer again with just me and that worked until my friend joined again. Then we tried it again and now mine still works after he joined but his does not work. 

There is definitely something weird going on.

Yesterday when I tested it it did not work if I was solo in my local multiplayer. But now it does and has a chance of not working as soon as my friend joins

**Comment by Timmeey86** [comment]
Is it possible for you to contact me on discord? Username is equal to my github username

**Comment by Timmeey86** [comment]
Otherwise you could try this version.
What I believe is happening is that when one player stows their chainsaw away, it also disables the F1 menu for anyone else on their server. I fixed that for dedicated servers but maybe it doesn't work for locally hosted once since one client is also the server and might receive more events than a client otherwise would.

I tried a new approach where I try to filter any events for the currently logged in player. 
[FS22_TreeValueInfo.zip](https://github.com/Timmeey86/FS22_ForestryHelper/files/14736362/FS22_TreeValueInfo.zip)
